### ISSUE TITLE
User permissions not loading error 

### ISSUE THREAD

**Issue by nishantbhat** [erxes/erxes#1028]
I instlled the erxes docker on my machine but team adding screen should not loading the permission dropdown with data .Am not getting why this is happening.Please help me to solve the problem .
![Screenshot from 2019-07-10 12-07-00-01](https://user-images.githubusercontent.com/30562513/60946707-82befb00-a30c-11e9-9f2b-b1043165189b.jpeg)

**Comment by shinebayar-g** [comment]
Hi @nishantbhat , Maybe it's related to database migration issue. Try to run `docker exec -it erxes-api yarn migrate` command in your erxes-api container.

**Comment by nishantbhat** [comment]
@shinebayar-g  thank you so much for the quick reply. How add multiple permission  types in the application  ? Is there complete usage guide for the application ??? It makes new user life easier.

**Comment by shinebayar-g** [comment]
@nishantbhat I just realized that you have to create your first permission before you invite anyone to your team since it's required field when inviting team member. To create permission go to **settings - Permission** tab. We're documenting our software at http://docs.erxes.io and its source code is maintained at https://github.com/erxes/docs. It maybe little bit outdated, but covers basics of the erxes app.

**Comment by nishantbhat** [comment]
Thanks a lot its working now.

**Comment by shinebayar-g** [comment]
Glad it worked for you. Make sure you're using our latest version 0.9.17. https://github.com/erxes/erxes/wiki/Use-erxes-with-Docker is little bit outdated. I'll be updating related documents very soon.
