### ISSUE TITLE
Erxes installation script for CentOS 8

### ISSUE THREAD

**Issue by batnasan** [erxes/erxes#1651]
**Is your feature request related to a problem? Please describe.**
When someone has a fresh **CentOS** system and wants to instal **erxes** on their server.
Doing everything manually is time-consuming and it can be frustrating as everyone does not have the proper knowledge to do so.

**Describe the solution you'd like**
It would be very useful to have a script to install **erxes** quickly on **CentOS**.

**Comment by mooreT1881** [comment]
I am replying to this email directly because I don't understand any of it and need any help in explaination.  Any information that I will be able to understand would be greatly appriciated.

Thomas P Moore

On Jan 31, 2020 5:58 AM, Batnasan Byambasuren <notifications@github.com> wrote:

Is your feature request related to a problem? Please describe.
When someone has a fresh CentOS system and wants to instal erxes on their server.
Doing everything manually is time-consuming and it can be frustrating as everyone does not have the proper knowledge to do so.

Describe the solution you'd like
It would be very useful to have a script to install erxes quickly on CentOS.

**Comment by shinebayar-g** [comment]
@mooreT1881 

looks like you're subscribed to our repository updates. If you don't want to receive such emails click on that Unwatch button then select Not watching option.

![image](https://user-images.githubusercontent.com/3091558/73586749-53720600-4477-11ea-8d32-440cea4e4e5b.png)
