### ISSUE TITLE
IMAP New Account doesn't get added

### ISSUE THREAD

**Issue by QuickTrans** [erxes/erxes#1855]
After creating a new IMAP account and clicking on save, it shows a load icon, but the window keeps the same after several minutes (so the account doesn't get added).
This can't be due to my credentials, I have tested them with other clients as well.

**Comment by munkhorgil** [comment]
Hello, @QuickTrans 
I have some questions to investigate this issue.
1. What IMAP Hosting do you use for your email?
2. Can you show me the screenshot of your browser's log when you click on the Save button?

**Comment by nicopace** [comment]
The same happens to me!

**Comment by Kalyse** [comment]
I get the same issue, and I've been trying to understand for a while the issue. 

The problem for me is that the graphql connection times out from the browser.
It's a 60 second timeout. I'm not sure how to diagnose what service isn't responding which would cause the timeout, but I'm happy to provide walk through of the problem. 

![Selection_999(338)](https://user-images.githubusercontent.com/199760/78073045-0edfe980-7398-11ea-8277-abd4342e46a9.png)

**Comment by mendorshikh** [comment]
@nicopace @Kalyse @QuickTrans Thank you for following up on the issue. @munkhorgil will resolve shortly and let u guys know.

**Comment by munkhorgil** [comment]
Hello @Kalyse, Can you show me the form you submit? It looks like your IMAP host is not correct, it should be something like imap.yourmail.com.

**Comment by munkhorgil** [comment]
@nicopace @Kalyse @QuickTrans 
Did you guys set ALGORITHM, ENCRYPTION_KEY in System configs? Because we asked the email's password so we need to encrypt the password.

**Comment by Kalyse** [comment]
@munkhorgil We can pick this up on RocketChat community if you would like. I'm "@Layke" on there. 

I'm motivated to get you the information you need. 

I posted a longer video on there, but here is the Nylas Imap example: 

https://www.loom.com/share/7f5df781900b425985cb3daf0c8064db

PS. The reason the host is not correct is because I was tired of entering the same live credentials 50+ times. The same issue happens with live creds, but it was also happening on the Nylas Google connection also. (Which is what I posted on the Erxes Rocket Chat community about). 

> ALGORITHM, ENCRYPTION_KEY

No, I did not set  this. From what I could tell from the documentation, this setting (following the documentation sounded as though it was limited to Microsoft Exchange integrations only?). Is this not the case?

**Comment by nicopace** [comment]
> @nicopace @Kalyse @QuickTrans
> Did you guys set ALGORITHM, ENCRYPTION_KEY in System configs? Because we asked the email's password so we need to encrypt the password.

There is no interface in the GUI for that.

**Comment by nicopace** [comment]
I am available for live testing if you need, I want this to be fixed. thanks!

**Comment by Kalyse** [comment]
@nicopace  

You need to create any 32 character string and add as your encryption key. 

If you look at erxes-integration-api.log you will see that there is a cipher error because it's not been set up with this information. 


![Selection_999(354)](https://user-images.githubusercontent.com/199760/78137136-ae46c000-741c-11ea-9dde-2e746ea529db.png)

**Comment by Layke** [comment]
@Kalyse, no need to tag someone directly even if that's your name on another service. `@Kalyse` works to give someone the info they need without causing unintended consequences. Good luck with your problem though guys! Hope they are able to resolve it.

**Comment by Kalyse** [comment]
> @Kalyse, no need to tag someone directly even if that's your name on another service. `@Kalyse` works to give someone the info they need without causing unintended consequences. Good luck with your problem though all! Hope they are able to resolve it.

Apologies. I agree, that was a totally unintended consequence. I'll edit the post to remove your reference.

**Comment by nicopace** [comment]
> @nicopace
> 
> You need to create any 32 character string and add as your encryption key.
> 
> If you look at erxes-integration-api.log you will see that there is a cipher error because it's not been set up with this information.

How do I do this in the erxes.io hosted version?

In my hosted version I don't have a System's config screen.... I used the code of a few weeks ago...

**Comment by munkhorgil** [comment]
Hey @nicopace, Are you available at [rocketchat](https://community.erxes.io/channel/public) since you are using the hosted version you could send DM there, I would be happy to help

**Comment by nicopace** [comment]
> Hey @nicopace, Are you available at [rocketchat](https://community.erxes.io/register/Gw4WRJnk9fSbyAXTq) since you are using the hosted version you could send DM there, I would be happy to help

tried to join rocketchat, but couldn't.
I am nicopace@altermundi.net on your support platform.
send me an invite and I can join.

**Comment by batamar** [comment]
Too old
