### ISSUE TITLE
Installation problems for Ubuntu

### ISSUE THREAD

**Issue by crowdfluence** [erxes/erxes#2053]
**Describe the bug**
Your very own installation instructions from this link aren't working.

https://www.erxes.org/installation/debian10/

**To Reproduce**
I'm just following your own instructions

**Expected behavior**
I expected to have a working script....and I do not.

**Screenshots**
![Screen Shot 2020-06-12 at 12 35 48 PM](https://user-images.githubusercontent.com/46536347/84525207-4842a880-aca9-11ea-84a2-3331f16173c5.jpg)

**Context (please include the related information if applicable):**
 - Ubunti 18.04
 - Mac terminal
 - erxes version - latest version
 - installation type - manual

**Comment by RileySeaburg** [comment]
I struggle with this issue as well. 

The best way around it that I found was to install mongodb beforehand and then run the installation script.

You'll also have to pre-create the home/erxes directory with root permissions.

**Comment by crowdfluence** [comment]
Thanks for this.....any tutorial on how to pre-create this directory?

**Comment by wayneoutthere** [comment]
ack... man.  it would have been nice to know everything is broken before beginning, haha.
For me, this failed at 'elasticsearch' stage on Ubuntu.  Then I tried Debian and ... failed at 'Rabbitmq' point of installation.

**Comment by wayneoutthere** [comment]
Update from my Digital Ocean debian droplet test:

```
root@debian-s-1vcpu-1gb-hub-deb10:~# systemctl status elasticsearch.service 
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/lib/systemd/system/elasticsearch.service; enabled; vendor pr
   Active: failed (Result: exit-code) since Mon 2020-07-06 13:02:12 UTC; 15min a
     Docs: https://www.elastic.co
  Process: 23000 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${
 Main PID: 23000 (code=exited, status=1/FAILURE)

Jul 06 13:02:12 debian-s-1vcpu-1gb-hub-deb10 systemd-entrypoint[23000]: error:
Jul 06 13:02:12 debian-s-1vcpu-1gb-hub-deb10 systemd-entrypoint[23000]: OpenJDK 
Jul 06 13:02:12 debian-s-1vcpu-1gb-hub-deb10 systemd-entrypoint[23000]:         
Jul 06 13:02:12 debian-s-1vcpu-1gb-hub-deb10 systemd-entrypoint[23000]:         
Jul 06 13:02:12 debian-s-1vcpu-1gb-hub-deb10 systemd-entrypoint[23000]:         
Jul 06 13:02:12 debian-s-1vcpu-1gb-hub-deb10 systemd-entrypoint[23000]:         
Jul 06 13:02:12 debian-s-1vcpu-1gb-hub-deb10 systemd-entrypoint[23000]:         
Jul 06 13:02:12 debian-s-1vcpu-1gb-hub-deb10 systemd[1]: elasticsearch.service: 
Jul 06 13:02:12 debian-s-1vcpu-1gb-hub-deb10 systemd[1]: elasticsearch.service: 
Jul 06 13:02:12 debian-s-1vcpu-1gb-hub-deb10 systemd[1]: Failed to start Elastic

```

**Comment by wayneoutthere** [comment]
Hey guys!  Thankfully open source software world is full of people much smarter than me, and someone suggested maybe my 1GB test server wasn't enough.  He was RIGHT.  I doubled to 2GB and everything started installing on the test Debian10 server.   I think you should put minimum hardware requirements somewhere front and center on [this page](https://www.erxes.org/installation/debian10/) and even before

**Comment by shinebayar-g** [comment]
Currently installation script is building source code from scratch rather than downloading compiled version. And building from source step eats ram, takes a while. This is a bad behavior, we're working on an improvement.  About hardware requirements there were some hardware recommendation page at some point but looks like it's lost.

**Comment by wayneoutthere** [comment]
no worries. just reporting my findings. I like this project indeed....

**Comment by shinebayar-g** [comment]
Okay just released a new version https://github.com/erxes/erxes/releases/tag/0.15.0 that includes compiled version assets in the release page. It's been broken for few releases. Now deployment script should be able to directly using this assets rather than building. Updated docs is also coming soon.

**Comment by wayneoutthere** [comment]
wow! you're amazing.  :)  Let's see if I can try install again....

**Comment by shinebayar-g** [comment]
We're almost getting there. There is only 1 issue left to solve and we're good to go. I think it'll be fixed by tomorrow.

**Comment by davidkartuzinski** [comment]
@wayneoutthere - Can you confirm that the installation issue has been resolved for you? That way we can close this issue.

**Comment by wayneoutthere** [comment]
Hi.  Thanks for the efforts.  Just so you know I won't be using erxes because of the 8GB ram requirement. That's way out of an SMB budget for this for now so I'll have to go searching for some less resource hungry options  as much as I really want to give this a try.  So, I can't invest more time into testing until that time, either.  However, for the records and for your efforts I gave it another test run and I got stuck at this command: ssh-copy-id erxes@your-IP-address  It simply wouldn't work. I'm using a digital ocean 8GB test droplet.  So, I continued the tutorial as root and using `su erxes` to try to work through it that way.

this also didn't work for me: 

`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
source ~/.bashrc`

Stopping there and thanks for the efforts! will follow project...

**Comment by davidkartuzinski** [comment]
I understand. And your feedback has been noted. I will take another look at the docs, and in the meantime, you might find the free tier or $20 per month tier on the SaaS product exactly what you need. I invite you to take a look there.

In the meantime, we will do our best to convince to get it a another at a future date.

I am closing the issue for now, feel free to talk to us in chat or to open another issue.
