### ISSUE TITLE
Difficulty in removing Account 

### ISSUE THREAD

**Issue by Cyberarray** [erxes/erxes#2157]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [e.g docker, manual]

**Additional context**

**Comment by davidkartuzinski** [comment]
@Cyberarray - This issue is not clear. Please complete the template and fully describe the issue. Otherwise we cannot act on it. I am closing this issue. If you update the description and complete the information for the template - we will be more than happy to reopen and take care of the issue. 

You need to replace the information in the template, like this:

![Screen Shot 2020-07-27 at 19 17 06](https://user-images.githubusercontent.com/29503118/88571455-f332da00-d03d-11ea-9516-69ba9c08619c.png)
