### ISSUE TITLE
Chat Sound and Browser Tab Notification

### ISSUE THREAD

**Issue by kang28ivan** [erxes/erxes#2181]
**Is your feature request related to a problem? Please describe.**
At this time for incoming chat notifications sometimes appear and sometimes do not appear and chat replies are not available so, when the visitors who replies to the chat, this does not have a notification at all to the agent including no sound ding/dong, so agents often miss replying to chats because they don't see the conversation page browser every time

**Describe the solution you'd like**
As explained above, we need a notification sound on each incoming chat and chat replies between agents and visitors also browser tab notification like a tawk.to when Engage is run, example like on the screenshot **1 New Message**
![Screenshot_5](https://user-images.githubusercontent.com/53988458/89098417-0668ef80-d41a-11ea-817c-28c60c36f212.png)

**Additional context**
that's all, maybe this can be considered for the next update because it's quite important feature chat reply notification.

Thank you 🙏

**Comment by davidkartuzinski** [comment]
@kang28ivan Thank you for your feedback.  These seems like a great area to improve. Can you clarify the way you're using erxes. It seems like your agents have erxes open in a tab but perhaps working in other tabs. You would like a better notification method so that your agents "catch" the messages. In this case, a "ding/dong" sound.  Is that correct?

How do you feel about:

1. Adding a little notification icon in the browser tab?
2. Allowing the browser to give a desktop message (like Facebook does)?
3. An optional sound (as you suggested) and like other applications do
4. We could also add an additional UI notification to show pending messanges in erxes

Can you clarify if you have one or multiple agents working at the same time on responding to the chat messages?

One issue we have, how to we handle if there are multiple agents working on chat? Should all of them be notified? Do you have any ideas on this?

Perhaps all the agents could be notified if no one has started the conversation with the user, but if Agent #1 started already, then only he could have the following notfiications? 

What are your thoughts on this?

Let me repeat, this is an excellent suggestion.

Thank you.

**Comment by davidkartuzinski** [comment]
@karser -suggested an email to the Agent/Operator if they are not logged in.  Perhaps this feature could be "logged in and active in the last 15 minutes".  @kang28ivan - what do you think about this? @ganzorig any thoughts?

**Comment by karser** [comment]
Erxes uses browser notifications and the sound is up to the OS. On my desktop (ubuntu 18.04) I hear the chat sound when the tab is not active.
But still it's hard to underestimate the importance of notifications, so auxiliary tools are never superfluous.

**Comment by davidkartuzinski** [comment]
> Erxes uses browser notifications and the sound is up to the OS. On my desktop (ubuntu 18.04) I hear the chat sound when the tab is not active.
> But still it's hard to underestimate the importance of notifications, so auxiliary tools are never superfluous.

@karser Thank you. I will wait to see if there is additional feedback.

**Comment by kang28ivan** [comment]
Hi @davidkartuzinski thank you, sir, in some cases the agent does not receive notifications such as a chat reply from the visitor (this happened several times) is this the fault of our browser or is the visitor too quick to reply, so there is no notice to us.

also when the agent replies to the chat the visitor does not receive a notification sound or running text on tab (I don't know how to explains it, but if it's on tawk.to when the tab is off the visitor gets a ring or text message running on the tab) 😅

1. I think this not about icon, i mean about notification when tab active or not active from visitor end and when agent reply.
2. I think yes, like a facebook or running text
![Screenshot_3](https://user-images.githubusercontent.com/53988458/89105005-27e4ce00-d450-11ea-8f9e-b1126b86e689.png)

3. That's right, previously accustomed to using tawk.to when the agent replies to visitor, visitor will receive a notification sound even though their tab is not active
4. This might be another option like that

> One issue we have, how to we handle if there are multiple agents working on chat? Should all of them be notified? Do you have any ideas on this?

I think now when the visitor chat is directed to some of member agents who will get notifications, right? So not all agents get notifications, only agent members are active in the conversation
![Screenshot_2](https://user-images.githubusercontent.com/53988458/89104641-5b722900-d44d-11ea-803f-3ff2c6ce1967.png)

> Perhaps all the agents could be notified if no one has started the conversation with the user, but if Agent #1 started already, then only he could have the following notfiications?

Yes, when agents are online they should get a notification when the visitor start conversation.

Sorry if my explanation confuses you, my English is bad 🙏
but basically there are only 2 features that I mean notification sound to visitors and running text on the tab

Thank you

**Comment by davidkartuzinski** [comment]
@karser Thank you for your clarification. (Your English is really good!) We will wait to see what anyone else thinks and then see if we can add this to our production timeline.
