### ISSUE TITLE
Open graph image falsely describes erxes as open source

### ISSUE THREAD

**Issue by martin-sweeny** [erxes/erxes#2538]
**Describe the bug**
The repository links to https://repository-images.githubusercontent.com/73453488/16231700-9542-11ea-8046-7049eb655e4b as the opengraph image for the repo, which describes erxes as open source. [As per the documentation](https://github.com/erxes/erxes#is-erxes-open-source), erxes is not open source.

**To Reproduce**
1. Share https://github.com/erxes/erxes on any major social platform which generates previews
2. Observe the graphic with false description

**Expected behavior**
An accurate description of the software's license, similar to the repo description or title.

**Screenshots**

![image](https://user-images.githubusercontent.com/3329959/102304812-58736300-3f2c-11eb-8736-60db74943621.png)
> Share preview as it appears on LinkedIn

**Comment by avats-dev** [comment]
I think the way to resolve this is to add a custom image (which will describe the repo best) in settings, as per the github docs on open graph. So, could not be done through a PR, I guess.

**Comment by martin-sweeny** [comment]
> I think the way to resolve this is to add a custom image (which will describe the repo best) in settings, as per the github docs on open graph. So, could not be done through a PR, I guess.

This is true

**Comment by timmwille** [comment]
this was a big downer actually, commons clause creates more problems then it solves. Still looks like a good tool, was hoping for a good new platform to checkout, just violating the GPL is apart from the unclear legal state of each contribution by community members quite full of conflict with other Open Source tools. So at least stating the not-so-obvious would be fair.

**Comment by mendorshikh** [comment]
Hey @timmwille, thanks for the feedback. Correct me if I'm wrong. 

The reason we are using the commons clause is only to protect from the hosting companies. Applying the Commons Clause to an open-source project will mean the source code is available and meets many of the elements of the Open Source Definition, such as free access to source code, freedom to modify, and freedom to re-distribute, but only forbids the hosting companies from “selling”. 

This is the idea. Period. Do you have a better idea? Please advise us.

**Comment by timmwille** [comment]
> Hey @timmwille, thanks for the feedback. Correct me if I'm wrong.
> 
> The reason we are using the commons clause is only to protect from the hosting companies. Applying the Commons Clause to an open-source project will mean the source code is available and meets many of the elements of the Open Source Definition, such as free access to source code, freedom to modify, and freedom to re-distribute, but only forbids the hosting companies from “selling”.
> 
> This is the idea. Period. Do you have a better idea? Please advise us.

It is in conflict with other Licenses, that causes a problem when you try to integrate it, even if you're a non-profit or not even plan to sell the hosted version. So in the Open Source Universe it becomes unusable. (I did not invent the copyright, so don't blame me, but calling it Open Source due to its conflicts is just confusing, I might put a lawyer onto this but currently I've settled with other options to save money and time. I'll get back to this maybe for another project with the option of checking the legal boundaries to walk around this issue in combination with other Licenses but I still would not call it Open Source if it does not fit into the definition. Can still be great software)

**Comment by marclaporte** [comment]
@mendorshikh 

The Open Source Definition (OSD) is here: https://opensource.org/osd/

As of now, Erxes is not Open Source. So every time the term is indicated on the site, it is false advertising. So you have to stop using the term Open Source or change the license to one of the approved OSD licenses.

Instead of Open Source, you can use the term "source available".

Best regards,

Marc

**Comment by mendorshikh** [comment]
@marclaporte We will correct using "source available" Thanks!
