### ISSUE TITLE
Integration with WhatsApp

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#3493]
[On-Premises API integration for WhatsApp so you do not need to pay for external services. As long as you have your own server you can also host the WhatsApp API client by shiznit](https://github.com/erxes/erxes/issues/3493)

**Comment by toaitrancodihaus** [comment]
- Even for cloud, we still can allow customer to put their own APP credentials to load there page/business only. Since asking for the public app (developer on behalf of customer) is hard, I have applied to Facebook for several times, never got replied

- Should only allow Whatsapp business, Whatsapp personal account might violate FB policy, and either our public app could be disabled and affect to other users, or the user would get banned account and lost access, due to we created a method for them to violate the policy
