### ISSUE TITLE
SLA plugins software requirements specification

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#3679]

**Comment by toaitrancodihaus** [comment]
Scenario: Organization already applied SLA policies to their workflow BEFORE using Erxes
GIVEN: Org want to apply those SLA policy to Erxes
WHEN: Agent have been assigning into a conversation/task/ticket/sale pipeline
THEN: Agent should only have a specific time frame to solve/reply the conversations, ticket.

===========
Possibilities:

- SLA should be configured as an addon so that it can be dependent configured for each task pipeline, ticket pipeline, channel, integration.
- SLA should be applied to enterprise only, SLA does not usually for small business -> erxes:ee add-on only
- Related to modules: inbox (built-in and 3rd integration)/tasks/sales/tickets, notifications and report
- Possible related in core: queueing, mailer, push notifications, agent member, hooks

============

Flow:

- Access module
- Create SLA policy
- Select module that SLA would be applied to
- Choose channel/integration/brand or pipeline to apply
- Select the type of SLA: time based, trigger based
- Select action: send push notification, send email reminder
- Testing & save
