### ISSUE TITLE
Marketplace on self hosted instance

### ISSUE THREAD

**Issue by radaniba** [erxes/erxes#3923]
Hi everyone
I am testing erxes on a fresh install (docker) locally, everything worked fine except that the fresh install has nothing configured which I guess needs to be built one at a time

That said, the marketplace page keeps loading constantly without loading anything, I am not sure whether or not this is becuase of the self hosted version but is there a straightforward way of installing plugins ? and how do we know which ones are installed by default?

Thanks

**Comment by nomio19** [comment]
Hello @radaniba , our DevOps @Myagmarsuren-a will follow up this issue.

**Comment by Myagmarsuren-a** [comment]
@radaniba Hello its me again. It UI plugin install feature works fine on other opensources. If yours does not work, first it must be ubuntu 22.04. Lets start from that does your machine meets this requirement .

**Comment by radaniba** [comment]
Thank you @Myagmarsuren-a  that must be it then, I am working based on my mac laptop, but still based on the docker images, I assume this might work ? No ?

**Comment by Myagmarsuren-a** [comment]
@radaniba yeah that does not work. But ill notify you its been changed or are you in our discord channel?

**Comment by radaniba** [comment]
no not yet @Myagmarsuren-a

**Comment by radaniba** [comment]
would that work on Fedora ?

**Comment by Myagmarsuren-a** [comment]
@radaniba i dont think so . Please join our discord https://discord.gg/qp9rUbQj

**Comment by wchesley** [comment]
I too had this issue on a fresh install, I am posting a resolution to this issue here as it's not explicitly written out. Thanks to this issue though, I was able to resolve mine. Please correct me if I am wrong: 

From what I understand, so long as the plugin files exist in `/erxes/packages` you can specify them in your `configs.json`, under the plugins array. Aside from just adding the plugin, I had to specify `"ui": "local"` before I saw the plugins in erxes dashboard.
