### ISSUE TITLE
Multi-tenant

### ISSUE THREAD

**Issue by mariusa** [erxes/erxes#4001]
Hi, do you support Multi-tenant?

That is, hosting multiple businesses on the same instance & db schema. Each business has their own customers/contacts etc.
If not, are there plans to add this? Multi-tenant is a very common requested feature on other major open source SaaSes, and the longer this waits, the more complex it gets to be implemented. Same for i18n.

Thanks!

**Comment by mendorshikh** [comment]
@mariusa Hi there! HNY! Thank you for your question.

In regards to your inquiry about multi-tenancy, I'd like to first let you know that you can find information about our licensing at https://github.com/erxes/erxes/blob/master/LICENSE.md.

To answer your question, it seems that erxes is not currently permitted to be hosted as a Software-as-a-Service (SaaS) version in order to compete with erxes Inc. As such, it does not currently have a multi-tenancy option available. I apologize for any inconvenience this may cause. If you have any further questions or concerns, please don't hesitate to ask.

**Comment by mariusa** [comment]
Thanks for clarification!
