### ISSUE TITLE
502 bad gateway after docker setup guide

### ISSUE THREAD

**Issue by TwoBrake** [erxes/erxes#4085]
**Describe the bug**
I have followed the deploy on docker setup guide and everything seemed to start as expected, there are no errors after starting the container, but when I head to the domain I setup, it just says 502 bad gateway.

I believe this issue may be due to port 3000 being taken, but I am not sure. If there is a way, can you tell me how to change the default ports as I don't understand how the documentation explains how to?

**To Reproduce**
1. Follow the deploy on docker setup guide.
2. Go to the domain you setup.

**Comment by Myagmarsuren-a** [comment]
@TwoBrake Its known issue we are working on it. Fix is just simply create folder named <locales> in erxes directory. Then start erxes.

**Comment by stepcellwolf** [comment]
Hi, 
I'm having the same issue. What do you me by create folder named in erxes directory?
I followed the all above steps and also removed containers and run them again, re-upload certification but still the same issue? 

Thanks in advance.

**Comment by nitish2507** [comment]
Hi - I am facing the same issue, on checking the logs, I see that it seems to be an issue with GraphQL.

See error details below

`Clearing enabled services cache ........
(node:1) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:1) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:1) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
Plugin contacts joined service discovery.
Plugin notifications joined service discovery.
Plugin workers joined service discovery.
Plugin forms joined service discovery.
Plugin integrations joined service discovery.
Plugin emailtemplates joined service discovery.
Plugin logs joined service discovery.
Plugin cards joined service discovery.
Plugin inbox joined service discovery.
Plugin webbuilder joined service discovery.
Plugin internalnotes joined service discovery.
Plugin core joined service discovery.
Plugin segments joined service discovery.
Plugin products joined service discovery.
Plugin tags joined service discovery.
Plugin engages joined service discovery.
Plugin knowledgebase joined service discovery.
Plugin contacts's graphql endpoint http://plugin_contacts_api/graphql is up.
Plugin notifications's graphql endpoint http://plugin_notifications_api/graphql is up.
Plugin workers's graphql endpoint http://plugin_workers_api/graphql is up.
Plugin forms's graphql endpoint http://plugin_forms_api/graphql is up.
Plugin integrations's graphql endpoint http://plugin_integrations_api/graphql is up.
Plugin emailtemplates's graphql endpoint http://plugin_emailtemplates_api/graphql is up.
Plugin logs's graphql endpoint http://plugin_logs_api/graphql is up.
Plugin webbuilder's graphql endpoint http://plugin_webbuilder_api/graphql is up.
Plugin core's graphql endpoint http://plugin_core_api/graphql is up.
Plugin cards's graphql endpoint http://plugin_cards_api/graphql is up.
Plugin inbox's graphql endpoint http://plugin_inbox_api/graphql is up.
Plugin internalnotes's graphql endpoint http://plugin_internalnotes_api/graphql is up.
Plugin engages's graphql endpoint http://plugin_engages_api/graphql is up.
Plugin segments's graphql endpoint http://plugin_segments_api/graphql is up.
Plugin tags's graphql endpoint http://plugin_tags_api/graphql is up.
Plugin products's graphql endpoint http://plugin_products_api/graphql is up.
Plugin knowledgebase's graphql endpoint http://plugin_knowledgebase_api/graphql is up.
There is a newer version of Rover available: v0.14.1 (currently running v0.14.0)

For instructions on how to install, run `rover docs open start`
resolving SDL for subgraphs defined in /erxes-gateway/dist/gateway/src/apollo-router/temp/supergraph.yaml
error[E038]: Encountered 17 build errors while trying to build a supergraph.

Caused by:
    E028: error sending request for url (http://plugin_cards_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'cards' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_contacts_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'contacts' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_core_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'core' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_emailtemplates_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'emailtemplates' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_engages_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'engages' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_forms_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'forms' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_inbox_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'inbox' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_integrations_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'integrations' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_internalnotes_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'internalnotes' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_knowledgebase_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'knowledgebase' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_logs_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'logs' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_notifications_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'notifications' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_products_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'products' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_segments_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'segments' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_tags_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'tags' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_webbuilder_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'webbuilder' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_workers_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'workers' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    
        See https://www.apollographql.com/docs/rover/commands/supergraphs#yaml-configuration-file for information on the config format.
(node:1) UnhandledPromiseRejectionWarning: Error: Command failed: rover supergraph compose --config /erxes-gateway/dist/gateway/src/apollo-router/temp/supergraph.yaml --output /erxes-gateway/dist/gateway/src/apollo-router/temp/supergraph.graphql --elv2-license=accept --log=error
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at /erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:59:38
    at Generator.next (<anonymous>)
    at /erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:4:12)
    at supergraphComposeOnce (/erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:53:37)
    at /erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:82:15
    at Generator.next (<anonymous>)
    at fulfilled (/erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by vinyll** [comment]
Hey guyz,
Did you solve or find a workaround?
I'm not sure how to apply "create folder named in erxes directory", any idea how to solve?
🫡

**Comment by TwoBrake** [comment]
You need to create a folder called "erxes" in the root directory of the installation and put the content inside of that. If I remember correctly, these should be the correct steps to fix this issue.
