### ISSUE TITLE
General system config -> Upload service type -> Local give a "Network error: Response not successful: Received status code 400"

### ISSUE THREAD

**Issue by nomio19** [erxes/erxes#4090]
- [ ] Need to check and fix

**Comment by Mambatukaa** [comment]
More explanation is required.

**Comment by NorkzYT** [comment]
@Mambatukaa 

If you go inside of Erxes, then into `Settings` => `General system config` => `File upload`, the only `Upload Service Type` which is called, `Local` does not work, and `AWS` does. I do not know about `GCS` though since I do not use it.

![image](https://user-images.githubusercontent.com/53381649/218191014-08f07045-9490-4646-b841-96eba7031cd1.png)

**Comment by Myagmarsuren-a** [comment]
@NorkzYT This is know issue gonna mark this as bug and close.
