### ISSUE TITLE
Chatbot development

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#719]

**Comment by veerjainATgmail** [comment]
Hi,
 
What is the current thinking on the approach?
Is it in progress? Can someone contribute to this feature?

MJ

**Comment by mendorshikh** [comment]
Hey @veerjainATgmail ,

> What is the current thinking on the approach?

First of all, we are planning to integrate with https://dialogflow.com/ or https://dev.botframework.com/ since our https://github.com/erxes/erxes-integrations integration is based on https://botkit.ai/.

> Is it in progress?
Not yet but very soon.

> Can someone contribute to this feature?
I would encourage you to start with #HelpWanted https://github.com/erxes/erxes/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22 

PS: Did u join our slack? If not, please join via https://slack.erxes.io

MJ

**Comment by veerjainATgmail** [comment]
Hi @mendorshikh , Thanks for the quick response. Shall join your slack group.

**Comment by indraganzorig** [comment]
Hey there,

This is in the long-term pipelines.

We've moved our enhancement/feature requests into https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.

**Comment by davidkartuzinski** [comment]
@indraganzorig I didn't see this in productboard. Could you please add it? That way we can get additional feedback and votes for this feature!  Thank you.

**Comment by davidkartuzinski** [comment]
@veerjainATgmail - Please see https://roadmap.erxes.io/c/23-conversational-bots?utm_medium=social&utm_source=portal_share and if you still would like to see this feature developed, vote on it. I am closing this issue.
